[project]
name = "sps_genai"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "uvicorn",
    "pillow",
    "numpy",
    "torch",
    "torchvision",
    "tqdm>=4.66.0",
    "python-multipart>=0.0.20",

    # LLM 依赖
    "transformers>=4.44.0",
    "datasets>=2.20.0",
    "accelerate>=1.0.0",
]
