import base64
import io
from typing import Dict
from pathlib import Path

import torch
from fastapi import APIRouter, HTTPException
from PIL import Image
from torchvision.utils import make_grid
from torchvision import transforms

from .diffusion_model import SimpleUNet, DDPM

router = APIRouter(prefix="/diffusion", tags=["Diffusion Model"])

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

unet = SimpleUNet(in_channels=3, base_channels=64, time_dim=256)
diffusion = DDPM(unet, timesteps=1000)

# ✔ 统一与 Energy / GAN / CNN 的路径一致
CKPT_PATH = Path(__file__).resolve().parent / "models" / "diffusion_cifar10.pth"

DIFFUSION_AVAILABLE = False
try:
    state = torch.load(CKPT_PATH, map_location=DEVICE)
    diffusion.load_state_dict(state)
    diffusion.to(DEVICE)
    diffusion.eval()
    DIFFUSION_AVAILABLE = True
    print(f"[Diffusion] Loaded checkpoint from {CKPT_PATH}")
except FileNotFoundError:
    print(f"[Diffusion] WARNING: checkpoint {CKPT_PATH} not found.")

denorm = transforms.Normalize(
    mean=[-1, -1, -1],
    std=[2, 2, 2],
)

def tensor_to_base64_grid(x: torch.Tensor) -> str:
    x = denorm(x)
    grid = make_grid(x, nrow=int(x.size(0) ** 0.5), padding=2)
    grid = (grid.clamp(0, 1) * 255).permute(1, 2, 0).byte().cpu().numpy()
    img = Image.fromarray(grid)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode("utf-8")

@router.post("/generate")
async def generate_images(batch_size: int = 16) -> Dict:
    if not DIFFUSION_AVAILABLE:
        raise HTTPException(
            status_code=500,
            detail="Diffusion checkpoint not found. Train the model first.",
        )

    with torch.no_grad():
        x = diffusion.sample(batch_size=batch_size, device=DEVICE)

    img_b64 = tensor_to_base64_grid(x)

    return {
        "batch_size": batch_size,
        "image_png_base64": img_b64,
        "note": "Grid of CIFAR10-like images generated by diffusion model.",
    }
